### ISSUE TITLE
Update Visual Studio solution and projects to Visual Studio 2022

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#999]
This will also require updating the Windows SDK targets. I deliberately did not install the WIndows 11 SDK (10.0.22000.0) because my current computer does not support it (no TPM 2.0, yet) and only installed the latest Windows 10 SDK (10.0.20348.0) along-side version 10.0.19041.0 (this lower version is required for some of the modules I use.)

**Comment by cugone** [comment]
Turns out both AppVeyor CI and Unreal Engine 5.0 (Preview) don't yet support Visual Studio 2022 (I expect UE5 to by its full release) so I'm in the process of *re*-installing 2019 then 2022 (I'm paranoid that something will break, so side-by-side installs must be done in order.)

**Comment by DanRStevens** [comment]
Reference: https://github.com/OutpostUniverse/OPHD/pull/1184

Looks like GitHub Actions can also do Windows builds, and there is a environment available for a preview of VS2022. This may be an alternative to using AppVeyor. Might even be better too, since it offers parallel builds on the free plan.

**Comment by DanRStevens** [comment]
I tried rebasing cugone's work into a `updateToVS2022` branch. It produced peculiar build errors that seemed to indicate a problem within the standard library while building the `test-graphics` project. I'm not really sure what to do about it. The error message doesn't give a source line in the project file.

A preview of the changes and link to the build error can be found at:
https://github.com/lairworks/nas2d-core/compare/main...updateToVS2022

Example error message:
https://github.com/lairworks/nas2d-core/runs/7714848913?check_suite_focus=true
> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\xmemory(56,20): error C2220: the following warning is treated as an error (compiling source file TestGraphics.cpp) [D:\a\nas2d-core\nas2d-core\test-graphics\test-graphics.vcxproj]
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31[326](https://github.com/lairworks/nas2d-core/runs/7714848913?check_suite_focus=true#step:6:327)\include\xmemory(56,20): error C4189: '_Overflow_is_possible': local variable is initialized but not referenced (compiling source file TestGraphics.cpp) [D:\a\nas2d-core\nas2d-core\test-graphics\test-graphics.vcxproj]

**Comment by cugone** [comment]
I've been getting hundreds of warnings coupled to thousands of messages referring to this exact issue in my own projects for *months* now and have yet to find out why. I can't even reproduce the problem as trying to reduce the code down to a MCVE makes the warnings/messages go away. From what I can gather it has something to to with `std::vector`, the contained type, and the destructor failing.

**Comment by cugone** [comment]
If you follow the message-chain that appears after the first warning it will eventually reference user-code.

**Comment by cugone** [comment]
@DanRStevens Visual Studio 2022 17.3 was released today and fixes the problem. Deleting all temporary files and doing a clean and re-build of the project successfully built with no errors, warnings, or messages.

**Comment by DanRStevens** [comment]
That is very good news.

I assume that means we'll need to wait for AppVeyor/GitHub Actions to update their Windows images.

**Comment by cugone** [comment]
> 
> I assume that means we'll need to wait for AppVeyor/GitHub Actions to update their Windows images.

Unfortunately. Based on previous experience, it might be between 1-3 months for AppVeyor to update. They just updated to 17.2.6 last week and that was released publicly a month ago. It was longer for the switch from VS2019 to VS2022 when that was released.

**Comment by DanRStevens** [comment]
Looks like GitHub Actions has updated their build images to 17.3 about 4 days ago:
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

The build logs also show it's now running `msbuild` 17.3:
https://github.com/lairworks/nas2d-core/runs/7938172747?check_suite_focus=true

Unfortunately, the stated error continues to persist.
> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\xmemory(56,20): error C2220: the following warning is treated as an error (compiling source file TestGraphics.cpp) [D:\a\nas2d-core\nas2d-core\test-graphics\test-graphics.vcxproj]
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include\xmemory(56,20): error C4189: '_Overflow_is_possible': local variable is initialized but not referenced (compiling source file TestGraphics.cpp) [D:\a\nas2d-core\nas2d-core\test-graphics\test-graphics.vcxproj]

**Comment by cugone** [comment]
Just as a precaution, does Github Actions cache *anything*? Is it possible to do a complete wipe of all temporary files then a clean and complete rebuild?

**Comment by DanRStevens** [comment]
I was thinking similar. The `vcpkg` builds are cached. Maybe a rebuild of those would help.

Any way to verify the problem is fixed for local builds with 17.3? Since the problem is a warning, it will only appear during the first build, and then won't appear during future builds that don't need to rebuild that file. That can make warnings appears to be fixed when actually they would still be present if a full rebuild is done.

**Comment by DanRStevens** [comment]
Seeing as how the build finally passed with the most recent Windows build environment, I wanted to take a moment to record a few details.

Branch build logs:
https://github.com/lairworks/nas2d-core/actions/workflows/msbuild.yml?query=branch%3AupdateToVS2022

Example runs:
- Passing: https://github.com/lairworks/nas2d-core/runs/8106619905?check_suite_focus=true
- Last failing: https://github.com/lairworks/nas2d-core/runs/7938172747?check_suite_focus=true

Passing environment:
- Operating system
  - Microsoft Windows Server 2022
  - 10.0.20348
  - Datacenter
- Runner Image
  - Image: windows-2022
  - Version: 20220828.1
  - Included Software: https://github.com/actions/runner-images/blob/win22/20220828.1/images/win/Windows2022-Readme.md
  - Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20220828.1
- MSBuild version 17.3.1+2badb37d1 for .NET Framework

Last failing environment:
- Operating System
  - Microsoft Windows Server 2022
  - 10.0.20348
  - Datacenter
- Runner Image
  - Image: windows-2022
  - Version: 20220816.1
  - Included Software: https://github.com/actions/runner-images/blob/win22/2022016.1/images/win/Windows2022-Readme.md
  - Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20220816.1
- MSBuild version 17.3.0+f67e3d35e for .NET Framework

**Comment by cugone** [comment]
AppVeyor [updated to VS2022 17.3.2](https://www.appveyor.com/updates/) on August 19.

**Comment by DanRStevens** [comment]
Btw, we disabled the AppVeyor builds for NAS2D and OPHD. We have Windows builds working on GitHub Actions for these projects. The GitHub Actions workflows run in parallel, whereas AppVeyor did the builds serially. This means the GitHub Actions workflows were significantly faster and less prone to getting bogged down if a bunch of things were pushed or merged at once.

**Comment by cugone** [comment]
That's great news.
